package com.ntv.ntvcons_backend.constants;

public enum SearchType {
    /* FileType */
    FILE_TYPE_BY_ID,
    FILE_TYPE_BY_NAME,
    FILE_TYPE_BY_NAME_CONTAINS,
    FILE_TYPE_BY_EXTENSION,
    FILE_TYPE_BY_EXTENSION_CONTAINS,

    /* Report */
    REPORT_BY_ID,
    REPORT_BY_PROJECT_ID,
    REPORT_BY_REPORTER_ID,
    REPORT_BY_REPORT_TYPE_ID,
    REPORT_BY_NAME,
    REPORT_BY_NAME_CONTAINS,
    REPORT_BY_REPORT_DATE,

    /* ReportType */
    REPORT_TYPE_BY_ID,
    REPORT_TYPE_BY_NAME,
    REPORT_TYPE_BY_NAME_CONTAINS,

    /* RequestType */
    REQUEST_TYPE_BY_ID,
    REQUEST_TYPE_BY_NAME,
    REQUEST_TYPE_BY_NAME_CONTAINS,

    /* User */
    USER_BY_ID,
    USER_BY_ROLE_ID,
    USER_BY_USERNAME,
    USER_BY_USERNAME_CONTAINS,
    USER_BY_PHONE,
    USER_BY_PHONE_CONTAINS,

    /* Role */
    ROLE_BY_ID,
    ROLE_BY_NAME,
    ROLE_BY_NAME_CONTAINS,

    /* Task */
    TASK_BY_ID,
    TASK_BY_NAME_CONTAINS,
    TASK_BY_PROJECT_ID,
    TASK_BY_PLAN_START_DATE,
    TASK_BY_PLAN_END_DATE,
    TASK_BY_ACTUAL_START_DATE,
    TASK_BY_ACTUAL_END_DATE,

    /* TasAssignment */
    TASK_ASSIGNMENT_BY_ID,
    TASK_ASSIGNMENT_BY_TASK_ID,
    TASK_ASSIGNMENT_BY_ASSIGNER_ID,
    TASK_ASSIGNMENT_BY_ASSIGNEE_ID,
    TASK_ASSIGNMENT_BY_ASSIGN_DATE,
    TASK_ASSIGNMENT_BY_REMOVE_DATE,
}
